### ISSUE TITLE
fix: URL der Posts weicht noch ab

### ISSUE THREAD

**Issue by cburgdorf** [sasteg/blog#1]
Die Struktur der URLs im aktuellen Blog lautet:

`/category/year/month/day/name-of-post.html`

also Beispielsweise:

`/angular/2017/02/27/three-things-you-didnt-know-about-the-async-pipe.html`

Wobei das `.html` optional ist und der Link auch ohne `.html` funktioniert.

Im neuen Blog sieht die URL aktuell noch so aus.

`/2017/02/21/using-zones-in-angular-for-better-performance/`

Es fehlt also die Kategorie und außerdem funktioniet die URL nicht mit `.html` suffix.

Mögliche Lösungen:

1. URL Struktur anpassen (wünschenswert)

2. Redirects

**Comment by Crux4711** [comment]
Fix in _config.yml 
:category in permalink 
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://blog.thoughtram.io
root: /
permalink: :category/:year/:month/:day/:title.html
permalink_defaults:
