### ISSUE TITLE
Wie funktionieren parametrisierte Fragmente

### ISSUE THREAD

**Issue by cburgdorf** [sasteg/blog#2]
Wir müssen rausfinden, wie man HTML Fragmente anlegen kann, an die ggf. auch Parameter übergeben werden.

Ein Fragment könnte z.B. so aussehen:

```
<div>
  <span>{{author.name}}</span> written on <span>{{post.date}}</span>
</div>
```

Und wenn man es benutzt ruft man es entsprechend mit den Parametern auf.

Pseudosyntax:

`include myfragment.html author, post`

**Comment by sasteg** [comment]
```
<%= post.author %>
<%= post.date %>
```

Eigene Fragmente:
Helper oder Partial

Helper:
siehe  #3 

Für Partial:
`/themes/thtrm-theme/layout/_partial/[path]/[to]/[partial]/[filename].ejs`

In [filename.ejs]:
- html
- js Fragmente
- Verarbeiten von übergebenen Parametern

Usage:
`<%- partial('_partial/[path]/[to]/[partial]/[filename]', {arg: param} %>`
