### ISSUE TITLE
Wie funktionieren Helper Funktionen

### ISSUE THREAD

**Issue by cburgdorf** [sasteg/blog#3]
Wichtig wäre auch zu wissen, wie wir Helper Funktionen schreiben können, die wir aus den Templates benutzen können.

Also Beispielsweise

```
function formatReadingTime(post) {
  let readingTime = doSomeMath(post);
  return `Average reading time of ${readingTime.minutes} and ${readingTime.seconds}`
}
```

Und dann im post irgendwo.

```
<span>helper.formatReadingTime(post)</span>
```

**Comment by sasteg** [comment]
`themes/thtrm-theme/scripts/[filename].js` 

In [filename].js:
```
hexo.extend.helper.register('helperName', function(args[]) {
  //do work
  //return something
}
```

Usage:
`<%- helperName(args) %>`
